baseURL = "http://r-toulouse.netlify.com/"
languageCode = "fr-fr"
title = "R Toulouse"
theme = "minimal"
# disqusShortname = "username" # delete this to disable disqus comments
# googleAnalytics = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[params]
    author = "R Toulouse"
    description = "R User Group Toulouse"
    description_fr = "Groupe d'utilisatrices et d'utilisateurs de R de Toulouse"
    githubUsername = "R-Toulouse"
    accent = "#FF5599"
    profilePic = "/img/logo.svg"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "solarized-dark"
    highlightLanguages = ["R", "go", "haskell", "kotlin", "scala", "swift"]

[[menu.main]]
    url = "/"
    name = "Accueil"
    weight = 1

[[menu.main]]
    url = "/evenements/"
    name = "Évènement"
    weight = 2

[[menu.main]]
    url = "/a-propos/"
    name = "À propos"
    weight = 3

[[menu.main]]
    url = "/code-de-conduite/"
    name = "Code de conduite"
    weight = 4


# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

[[menu.icon]]
    url = "https://twitter.com/RUG_Toulouse"
    name = "twitter"
    weight = 1

[[menu.icon]]
    url = "https://github.com/R-Toulouse"
    name = "github"
    weight = 2

[[menu.icon]]
    url = "https://r-toulouse.slack.com"
    name = "slack"
    weight = 3

[[menu.icon]]
    url = "mailto:rug.toulouse@gmail.com"
    name = "envelope-o"
    weight = 4
